# fly.toml app configuration file generated for travel-application on 2024-12-11T00:47:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'travel-application'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
