# fly.toml app configuration file generated for fly-io-deploy on 2024-12-02T23:09:04+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-io-deploy'
primary_region = 'nrt'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
